server:
  port: 8081
  servlet:
    context-path: /sell
spring:
  datasource:
    username: root
    password: zhangke12289
    url: jdbc:mysql://180.76.172.198/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.1.136
    port: 6379
  jpa:
    show-sql: true