spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    show-sql: true
  jackson:
    default-property-inclusion: non_null
#上面的配置 意思是返回的json数据是null的就不返回
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wxf2fef5eb1f9fcbb3
  mpAppSecret: 315387c74b75e4df78f75ec09250a9ac
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://myayif.natappfree.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://76z8bx.natappfree.cc
  wechatOpenAuthorize: http://76z8bx.natappfree.cc
  sell: http://76z8bx.natappfree.cc
#配置mybatis输出sql语句
logging:
  level:
    com.sell.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml